#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 128
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_SEMI = 1,
  anon_sym_LT_DASH = 2,
  anon_sym_checkif = 3,
  anon_sym_checkall = 4,
  anon_sym_or = 5,
  anon_sym_allowif = 6,
  anon_sym_denyif = 7,
  anon_sym_COMMA = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  anon_sym_true = 11,
  anon_sym_false = 12,
  sym_bytes = 13,
  sym_number = 14,
  sym_date = 15,
  sym_string = 16,
  anon_sym_LBRACK = 17,
  anon_sym_RBRACK = 18,
  anon_sym_ = 19,
  anon_sym_TAB = 20,
  anon_sym_LF = 21,
  aux_sym_nname_token1 = 22,
  aux_sym_nname_token2 = 23,
  anon_sym_DOLLAR = 24,
  sym_source_file = 25,
  sym_authorizer_element = 26,
  sym_rule = 27,
  sym_check = 28,
  sym_policy = 29,
  sym_rule_body = 30,
  sym_predicate = 31,
  sym_fact = 32,
  sym_expression = 33,
  sym_term = 34,
  sym_fact_term = 35,
  sym_set_term = 36,
  sym_boolean = 37,
  sym_set = 38,
  sym_sp = 39,
  sym_nname = 40,
  sym_variable = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_check_repeat1 = 43,
  aux_sym_rule_body_repeat1 = 44,
  aux_sym_predicate_repeat1 = 45,
  aux_sym_fact_repeat1 = 46,
  aux_sym_set_repeat1 = 47,
  aux_sym_sp_repeat1 = 48,
  aux_sym_nname_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_checkif] = "check if",
  [anon_sym_checkall] = "check all",
  [anon_sym_or] = "or",
  [anon_sym_allowif] = "allow if",
  [anon_sym_denyif] = "deny if",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_bytes] = "bytes",
  [sym_number] = "number",
  [sym_date] = "date",
  [sym_string] = "string",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_] = " ",
  [anon_sym_TAB] = "\t",
  [anon_sym_LF] = "\n",
  [aux_sym_nname_token1] = "nname_token1",
  [aux_sym_nname_token2] = "nname_token2",
  [anon_sym_DOLLAR] = "$",
  [sym_source_file] = "source_file",
  [sym_authorizer_element] = "authorizer_element",
  [sym_rule] = "rule",
  [sym_check] = "check",
  [sym_policy] = "policy",
  [sym_rule_body] = "rule_body",
  [sym_predicate] = "predicate",
  [sym_fact] = "fact",
  [sym_expression] = "expression",
  [sym_term] = "term",
  [sym_fact_term] = "fact_term",
  [sym_set_term] = "set_term",
  [sym_boolean] = "boolean",
  [sym_set] = "set",
  [sym_sp] = "sp",
  [sym_nname] = "nname",
  [sym_variable] = "variable",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_check_repeat1] = "check_repeat1",
  [aux_sym_rule_body_repeat1] = "rule_body_repeat1",
  [aux_sym_predicate_repeat1] = "predicate_repeat1",
  [aux_sym_fact_repeat1] = "fact_repeat1",
  [aux_sym_set_repeat1] = "set_repeat1",
  [aux_sym_sp_repeat1] = "sp_repeat1",
  [aux_sym_nname_repeat1] = "nname_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_checkif] = anon_sym_checkif,
  [anon_sym_checkall] = anon_sym_checkall,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_allowif] = anon_sym_allowif,
  [anon_sym_denyif] = anon_sym_denyif,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_bytes] = sym_bytes,
  [sym_number] = sym_number,
  [sym_date] = sym_date,
  [sym_string] = sym_string,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_] = anon_sym_,
  [anon_sym_TAB] = anon_sym_TAB,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym_nname_token1] = aux_sym_nname_token1,
  [aux_sym_nname_token2] = aux_sym_nname_token2,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_source_file] = sym_source_file,
  [sym_authorizer_element] = sym_authorizer_element,
  [sym_rule] = sym_rule,
  [sym_check] = sym_check,
  [sym_policy] = sym_policy,
  [sym_rule_body] = sym_rule_body,
  [sym_predicate] = sym_predicate,
  [sym_fact] = sym_fact,
  [sym_expression] = sym_expression,
  [sym_term] = sym_term,
  [sym_fact_term] = sym_fact_term,
  [sym_set_term] = sym_set_term,
  [sym_boolean] = sym_boolean,
  [sym_set] = sym_set,
  [sym_sp] = sym_sp,
  [sym_nname] = sym_nname,
  [sym_variable] = sym_variable,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_check_repeat1] = aux_sym_check_repeat1,
  [aux_sym_rule_body_repeat1] = aux_sym_rule_body_repeat1,
  [aux_sym_predicate_repeat1] = aux_sym_predicate_repeat1,
  [aux_sym_fact_repeat1] = aux_sym_fact_repeat1,
  [aux_sym_set_repeat1] = aux_sym_set_repeat1,
  [aux_sym_sp_repeat1] = aux_sym_sp_repeat1,
  [aux_sym_nname_repeat1] = aux_sym_nname_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_checkif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_checkall] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_allowif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_denyif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_bytes] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_date] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TAB] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_nname_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_nname_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_authorizer_element] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_check] = {
    .visible = true,
    .named = true,
  },
  [sym_policy] = {
    .visible = true,
    .named = true,
  },
  [sym_rule_body] = {
    .visible = true,
    .named = true,
  },
  [sym_predicate] = {
    .visible = true,
    .named = true,
  },
  [sym_fact] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_fact_term] = {
    .visible = true,
    .named = true,
  },
  [sym_set_term] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_sp] = {
    .visible = true,
    .named = true,
  },
  [sym_nname] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_check_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rule_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_predicate_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fact_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_set_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sp_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_nname_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 11,
  [22] = 22,
  [23] = 23,
  [24] = 11,
  [25] = 10,
  [26] = 10,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 37,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 36,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 50,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 58,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 56,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 36,
  [109] = 109,
  [110] = 110,
  [111] = 86,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 114,
  [116] = 39,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(61);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '$') ADVANCE(97);
      if (lookahead == '(') ADVANCE(70);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == ',') ADVANCE(69);
      if (lookahead == '-') ADVANCE(45);
      if (lookahead == ';') ADVANCE(62);
      if (lookahead == '<') ADVANCE(12);
      if (lookahead == '[') ADVANCE(83);
      if (lookahead == ']') ADVANCE(84);
      if (lookahead == ':' ||
          lookahead == '_') ADVANCE(95);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(86);
      if (lookahead == '\n') ADVANCE(87);
      if (lookahead == '\r') SKIP(1)
      if (lookahead == ' ') ADVANCE(85);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '$') ADVANCE(97);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == ',') ADVANCE(69);
      if (lookahead == '-') ADVANCE(45);
      if (lookahead == ';') ADVANCE(62);
      if (lookahead == '<') ADVANCE(12);
      if (lookahead == '[') ADVANCE(83);
      if (lookahead == ']') ADVANCE(84);
      if (lookahead == 'f') ADVANCE(89);
      if (lookahead == 'h') ADVANCE(91);
      if (lookahead == 't') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 2:
      if (lookahead == '\t') ADVANCE(86);
      if (lookahead == '\n') ADVANCE(87);
      if (lookahead == '\r') SKIP(2)
      if (lookahead == ' ') ADVANCE(85);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == ',') ADVANCE(69);
      if (lookahead == ';') ADVANCE(62);
      if (lookahead == '<') ADVANCE(12);
      if (lookahead == ']') ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 3:
      if (lookahead == '\t') ADVANCE(86);
      if (lookahead == '\n') ADVANCE(87);
      if (lookahead == '\r') SKIP(3)
      if (lookahead == ' ') ADVANCE(85);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == ',') ADVANCE(69);
      if (lookahead == ';') ADVANCE(62);
      if (lookahead == '<') ADVANCE(12);
      if (lookahead == ']') ADVANCE(84);
      if (lookahead == 'o') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 4:
      if (lookahead == '\t') ADVANCE(86);
      if (lookahead == '\n') ADVANCE(87);
      if (lookahead == '\r') SKIP(4)
      if (lookahead == ' ') ADVANCE(85);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == ',') ADVANCE(69);
      if (lookahead == ';') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '$') ADVANCE(97);
      if (lookahead == ',') ADVANCE(69);
      if (lookahead == '-') ADVANCE(45);
      if (lookahead == '[') ADVANCE(83);
      if (lookahead == ']') ADVANCE(84);
      if (lookahead == 'f') ADVANCE(89);
      if (lookahead == 'h') ADVANCE(91);
      if (lookahead == 't') ADVANCE(94);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(81);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '"') ADVANCE(82);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == '(') ADVANCE(70);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(11)
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 12:
      if (lookahead == '-') ADVANCE(63);
      END_STATE();
    case 13:
      if (lookahead == '-') ADVANCE(52);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(74);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(43);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(54);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(55);
      END_STATE();
    case 18:
      if (lookahead == 'T') ADVANCE(53);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(33);
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 24:
      if (lookahead == 'f') ADVANCE(68);
      END_STATE();
    case 25:
      if (lookahead == 'f') ADVANCE(67);
      END_STATE();
    case 26:
      if (lookahead == 'f') ADVANCE(64);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 29:
      if (lookahead == 'k') ADVANCE(6);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(65);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(40);
      END_STATE();
    case 35:
      if (lookahead == 'o') ADVANCE(38);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 37:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 38:
      if (lookahead == 'w') ADVANCE(7);
      END_STATE();
    case 39:
      if (lookahead == 'x') ADVANCE(14);
      END_STATE();
    case 40:
      if (lookahead == 'y') ADVANCE(5);
      END_STATE();
    case 41:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(57);
      if (lookahead == 'Z') ADVANCE(80);
      END_STATE();
    case 42:
      if (('0' <= lookahead && lookahead <= '2')) ADVANCE(41);
      END_STATE();
    case 43:
      if (('0' <= lookahead && lookahead <= '2')) ADVANCE(42);
      END_STATE();
    case 44:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(44)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 45:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      END_STATE();
    case 46:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 47:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 56:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 57:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 58:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(74);
      END_STATE();
    case 59:
      if (eof) ADVANCE(61);
      if (lookahead == '\t') ADVANCE(86);
      if (lookahead == '\n') ADVANCE(87);
      if (lookahead == '\r') SKIP(59)
      if (lookahead == ' ') ADVANCE(85);
      if (lookahead == 'a') ADVANCE(93);
      if (lookahead == 'c') ADVANCE(92);
      if (lookahead == 'd') ADVANCE(90);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 60:
      if (eof) ADVANCE(61);
      if (lookahead == 'a') ADVANCE(93);
      if (lookahead == 'c') ADVANCE(92);
      if (lookahead == 'd') ADVANCE(90);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(60)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_checkif);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_checkall);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_allowif);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_denyif);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_bytes);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(58);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '-') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_date);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(81);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_);
      if (lookahead == '\t') ADVANCE(86);
      if (lookahead == '\n') ADVANCE(87);
      if (lookahead == ' ') ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_TAB);
      if (lookahead == '\t') ADVANCE(86);
      if (lookahead == '\n') ADVANCE(87);
      if (lookahead == ' ') ADVANCE(85);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\t') ADVANCE(86);
      if (lookahead == '\n') ADVANCE(87);
      if (lookahead == ' ') ADVANCE(85);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_nname_token1);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_nname_token1);
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_nname_token1);
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_nname_token1);
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_nname_token1);
      if (lookahead == 'h') ADVANCE(21);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_nname_token1);
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_nname_token1);
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_nname_token2);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_nname_token2);
      if (lookahead == 'r') ADVANCE(66);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 60},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 60},
  [14] = {.lex_state = 60},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 59},
  [20] = {.lex_state = 59},
  [21] = {.lex_state = 59},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 59},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 8},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 60},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 60},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 3},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 44},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 44},
  [96] = {.lex_state = 44},
  [97] = {.lex_state = 44},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 44},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 11},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 11},
  [108] = {.lex_state = 11},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 11},
  [115] = {.lex_state = 11},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_nname_token1] = ACTIONS(1),
    [aux_sym_nname_token2] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(124),
    [sym_authorizer_element] = STATE(14),
    [sym_rule] = STATE(63),
    [sym_check] = STATE(63),
    [sym_policy] = STATE(63),
    [sym_predicate] = STATE(65),
    [sym_fact] = STATE(63),
    [sym_nname] = STATE(120),
    [aux_sym_source_file_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_checkif] = ACTIONS(5),
    [anon_sym_checkall] = ACTIONS(5),
    [anon_sym_allowif] = ACTIONS(7),
    [anon_sym_denyif] = ACTIONS(7),
    [aux_sym_nname_token1] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(9), 1,
      aux_sym_nname_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DOLLAR,
    STATE(8), 1,
      sym_sp,
    STATE(11), 1,
      aux_sym_sp_repeat1,
    STATE(76), 1,
      sym_term,
    STATE(122), 1,
      sym_nname,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(78), 2,
      sym_predicate,
      sym_expression,
    ACTIONS(17), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
    STATE(51), 3,
      sym_boolean,
      sym_set,
      sym_variable,
    ACTIONS(13), 4,
      sym_bytes,
      sym_number,
      sym_date,
      sym_string,
  [46] = 12,
    ACTIONS(9), 1,
      aux_sym_nname_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_DOLLAR,
    STATE(7), 1,
      sym_sp,
    STATE(11), 1,
      aux_sym_sp_repeat1,
    STATE(76), 1,
      sym_term,
    STATE(122), 1,
      sym_nname,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(78), 2,
      sym_predicate,
      sym_expression,
    ACTIONS(17), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
    STATE(51), 3,
      sym_boolean,
      sym_set,
      sym_variable,
    ACTIONS(13), 4,
      sym_bytes,
      sym_number,
      sym_date,
      sym_string,
  [92] = 11,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DOLLAR,
    STATE(11), 1,
      aux_sym_sp_repeat1,
    STATE(16), 1,
      sym_sp,
    STATE(43), 1,
      sym_term,
    STATE(44), 1,
      sym_fact_term,
    STATE(51), 1,
      sym_variable,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(84), 2,
      sym_boolean,
      sym_set,
    ACTIONS(17), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
    ACTIONS(23), 4,
      sym_bytes,
      sym_number,
      sym_date,
      sym_string,
  [133] = 9,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DOLLAR,
    STATE(11), 1,
      aux_sym_sp_repeat1,
    STATE(17), 1,
      sym_sp,
    STATE(82), 1,
      sym_term,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
    STATE(51), 3,
      sym_boolean,
      sym_set,
      sym_variable,
    ACTIONS(13), 4,
      sym_bytes,
      sym_number,
      sym_date,
      sym_string,
  [169] = 9,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DOLLAR,
    STATE(11), 1,
      aux_sym_sp_repeat1,
    STATE(18), 1,
      sym_sp,
    STATE(43), 1,
      sym_term,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
    STATE(51), 3,
      sym_boolean,
      sym_set,
      sym_variable,
    ACTIONS(13), 4,
      sym_bytes,
      sym_number,
      sym_date,
      sym_string,
  [205] = 10,
    ACTIONS(9), 1,
      aux_sym_nname_token1,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(29), 1,
      anon_sym_LBRACK,
    ACTIONS(31), 1,
      anon_sym_DOLLAR,
    STATE(76), 1,
      sym_term,
    STATE(122), 1,
      sym_nname,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(61), 2,
      sym_predicate,
      sym_expression,
    ACTIONS(27), 3,
      sym_bytes,
      sym_date,
      sym_string,
    STATE(51), 3,
      sym_boolean,
      sym_set,
      sym_variable,
  [242] = 10,
    ACTIONS(9), 1,
      aux_sym_nname_token1,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(29), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_DOLLAR,
    STATE(76), 1,
      sym_term,
    STATE(122), 1,
      sym_nname,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(61), 2,
      sym_predicate,
      sym_expression,
    ACTIONS(27), 3,
      sym_bytes,
      sym_date,
      sym_string,
    STATE(51), 3,
      sym_boolean,
      sym_set,
      sym_variable,
  [279] = 8,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    STATE(11), 1,
      aux_sym_sp_repeat1,
    STATE(22), 1,
      sym_sp,
    STATE(88), 1,
      sym_fact_term,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(87), 2,
      sym_boolean,
      sym_set,
    ACTIONS(17), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
    ACTIONS(35), 4,
      sym_bytes,
      sym_number,
      sym_date,
      sym_string,
  [311] = 3,
    STATE(10), 1,
      aux_sym_sp_repeat1,
    ACTIONS(39), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
    ACTIONS(37), 11,
      anon_sym_COMMA,
      anon_sym_true,
      anon_sym_false,
      sym_bytes,
      sym_number,
      sym_date,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_nname_token1,
      anon_sym_DOLLAR,
  [333] = 3,
    STATE(10), 1,
      aux_sym_sp_repeat1,
    ACTIONS(44), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
    ACTIONS(42), 11,
      anon_sym_COMMA,
      anon_sym_true,
      anon_sym_false,
      sym_bytes,
      sym_number,
      sym_date,
      sym_string,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      aux_sym_nname_token1,
      anon_sym_DOLLAR,
  [355] = 8,
    STATE(11), 1,
      aux_sym_sp_repeat1,
    STATE(23), 1,
      sym_sp,
    STATE(111), 1,
      sym_boolean,
    STATE(112), 1,
      sym_set_term,
    ACTIONS(46), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(48), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
    ACTIONS(50), 4,
      sym_bytes,
      sym_number,
      sym_date,
      sym_string,
  [387] = 8,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 1,
      aux_sym_nname_token1,
    STATE(65), 1,
      sym_predicate,
    STATE(120), 1,
      sym_nname,
    ACTIONS(54), 2,
      anon_sym_checkif,
      anon_sym_checkall,
    ACTIONS(57), 2,
      anon_sym_allowif,
      anon_sym_denyif,
    STATE(13), 2,
      sym_authorizer_element,
      aux_sym_source_file_repeat1,
    STATE(63), 4,
      sym_rule,
      sym_check,
      sym_policy,
      sym_fact,
  [418] = 8,
    ACTIONS(9), 1,
      aux_sym_nname_token1,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    STATE(65), 1,
      sym_predicate,
    STATE(120), 1,
      sym_nname,
    ACTIONS(5), 2,
      anon_sym_checkif,
      anon_sym_checkall,
    ACTIONS(7), 2,
      anon_sym_allowif,
      anon_sym_denyif,
    STATE(13), 2,
      sym_authorizer_element,
      aux_sym_source_file_repeat1,
    STATE(63), 4,
      sym_rule,
      sym_check,
      sym_policy,
      sym_fact,
  [449] = 8,
    ACTIONS(67), 1,
      anon_sym_RBRACK,
    STATE(11), 1,
      aux_sym_sp_repeat1,
    STATE(31), 1,
      sym_sp,
    STATE(42), 1,
      sym_set_term,
    STATE(86), 1,
      sym_boolean,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
    ACTIONS(65), 4,
      sym_bytes,
      sym_number,
      sym_date,
      sym_string,
  [480] = 9,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(29), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_DOLLAR,
    STATE(32), 1,
      sym_fact_term,
    STATE(33), 1,
      sym_term,
    STATE(51), 1,
      sym_variable,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(84), 2,
      sym_boolean,
      sym_set,
    ACTIONS(69), 3,
      sym_bytes,
      sym_date,
      sym_string,
  [512] = 7,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(29), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_DOLLAR,
    STATE(85), 1,
      sym_term,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 3,
      sym_bytes,
      sym_date,
      sym_string,
    STATE(51), 3,
      sym_boolean,
      sym_set,
      sym_variable,
  [539] = 7,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(29), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_DOLLAR,
    STATE(33), 1,
      sym_term,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 3,
      sym_bytes,
      sym_date,
      sym_string,
    STATE(51), 3,
      sym_boolean,
      sym_set,
      sym_variable,
  [566] = 5,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    STATE(21), 1,
      aux_sym_sp_repeat1,
    STATE(75), 1,
      sym_sp,
    ACTIONS(75), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
    ACTIONS(73), 5,
      anon_sym_checkif,
      anon_sym_checkall,
      anon_sym_allowif,
      anon_sym_denyif,
      aux_sym_nname_token1,
  [588] = 5,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    STATE(21), 1,
      aux_sym_sp_repeat1,
    STATE(68), 1,
      sym_sp,
    ACTIONS(75), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
    ACTIONS(79), 5,
      anon_sym_checkif,
      anon_sym_checkall,
      anon_sym_allowif,
      anon_sym_denyif,
      aux_sym_nname_token1,
  [610] = 4,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      aux_sym_sp_repeat1,
    ACTIONS(83), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
    ACTIONS(42), 5,
      anon_sym_checkif,
      anon_sym_checkall,
      anon_sym_allowif,
      anon_sym_denyif,
      aux_sym_nname_token1,
  [629] = 6,
    ACTIONS(29), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      sym_number,
    STATE(81), 1,
      sym_fact_term,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(87), 2,
      sym_boolean,
      sym_set,
    ACTIONS(85), 3,
      sym_bytes,
      sym_date,
      sym_string,
  [652] = 6,
    ACTIONS(50), 1,
      sym_number,
    STATE(111), 1,
      sym_boolean,
    STATE(113), 1,
      sym_set_term,
    ACTIONS(87), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(89), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(91), 3,
      sym_bytes,
      sym_date,
      sym_string,
  [675] = 3,
    STATE(26), 1,
      aux_sym_sp_repeat1,
    ACTIONS(93), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
    ACTIONS(42), 6,
      anon_sym_SEMI,
      anon_sym_LT_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_nname_token1,
  [692] = 4,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      aux_sym_sp_repeat1,
    ACTIONS(97), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
    ACTIONS(37), 5,
      anon_sym_checkif,
      anon_sym_checkall,
      anon_sym_allowif,
      anon_sym_denyif,
      aux_sym_nname_token1,
  [711] = 3,
    STATE(26), 1,
      aux_sym_sp_repeat1,
    ACTIONS(100), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
    ACTIONS(37), 6,
      anon_sym_SEMI,
      anon_sym_LT_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      aux_sym_nname_token1,
  [728] = 7,
    ACTIONS(9), 1,
      aux_sym_nname_token1,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(67), 1,
      sym_predicate,
    STATE(90), 1,
      sym_rule_body,
    STATE(96), 1,
      sym_sp,
    STATE(122), 1,
      sym_nname,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [752] = 7,
    ACTIONS(9), 1,
      aux_sym_nname_token1,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(58), 1,
      sym_predicate,
    STATE(69), 1,
      sym_rule_body,
    STATE(97), 1,
      sym_sp,
    STATE(122), 1,
      sym_nname,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [776] = 7,
    ACTIONS(9), 1,
      aux_sym_nname_token1,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(67), 1,
      sym_predicate,
    STATE(94), 1,
      sym_rule_body,
    STATE(95), 1,
      sym_sp,
    STATE(122), 1,
      sym_nname,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [800] = 7,
    ACTIONS(9), 1,
      aux_sym_nname_token1,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(58), 1,
      sym_predicate,
    STATE(66), 1,
      sym_rule_body,
    STATE(99), 1,
      sym_sp,
    STATE(122), 1,
      sym_nname,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [824] = 6,
    ACTIONS(65), 1,
      sym_number,
    ACTIONS(107), 1,
      anon_sym_RBRACK,
    STATE(40), 1,
      sym_set_term,
    STATE(86), 1,
      sym_boolean,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(105), 3,
      sym_bytes,
      sym_date,
      sym_string,
  [846] = 6,
    ACTIONS(109), 1,
      anon_sym_COMMA,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(45), 1,
      aux_sym_fact_repeat1,
    STATE(117), 1,
      sym_sp,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [867] = 6,
    ACTIONS(113), 1,
      anon_sym_COMMA,
    ACTIONS(115), 1,
      anon_sym_RPAREN,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(41), 1,
      aux_sym_predicate_repeat1,
    STATE(119), 1,
      sym_sp,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [888] = 6,
    ACTIONS(113), 1,
      anon_sym_COMMA,
    ACTIONS(115), 1,
      anon_sym_RPAREN,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(64), 1,
      aux_sym_predicate_repeat1,
    STATE(119), 1,
      sym_sp,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [909] = 6,
    ACTIONS(109), 1,
      anon_sym_COMMA,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(70), 1,
      aux_sym_fact_repeat1,
    STATE(117), 1,
      sym_sp,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [930] = 3,
    ACTIONS(119), 1,
      aux_sym_nname_token2,
    STATE(36), 1,
      aux_sym_nname_repeat1,
    ACTIONS(117), 6,
      anon_sym_SEMI,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [945] = 3,
    ACTIONS(124), 1,
      aux_sym_nname_token2,
    STATE(46), 1,
      aux_sym_nname_repeat1,
    ACTIONS(122), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [960] = 3,
    ACTIONS(126), 1,
      aux_sym_nname_token2,
    STATE(36), 1,
      aux_sym_nname_repeat1,
    ACTIONS(122), 6,
      anon_sym_SEMI,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [975] = 1,
    ACTIONS(128), 8,
      anon_sym_SEMI,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [986] = 6,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    ACTIONS(132), 1,
      anon_sym_RBRACK,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(102), 1,
      sym_sp,
    STATE(109), 1,
      aux_sym_set_repeat1,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1007] = 6,
    ACTIONS(113), 1,
      anon_sym_COMMA,
    ACTIONS(134), 1,
      anon_sym_RPAREN,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(64), 1,
      aux_sym_predicate_repeat1,
    STATE(118), 1,
      sym_sp,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1028] = 6,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    ACTIONS(136), 1,
      anon_sym_RBRACK,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(103), 1,
      aux_sym_set_repeat1,
    STATE(105), 1,
      sym_sp,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1049] = 6,
    ACTIONS(113), 1,
      anon_sym_COMMA,
    ACTIONS(138), 1,
      anon_sym_RPAREN,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(34), 1,
      aux_sym_predicate_repeat1,
    STATE(121), 1,
      sym_sp,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1070] = 6,
    ACTIONS(109), 1,
      anon_sym_COMMA,
    ACTIONS(140), 1,
      anon_sym_RPAREN,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(35), 1,
      aux_sym_fact_repeat1,
    STATE(123), 1,
      sym_sp,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1091] = 6,
    ACTIONS(109), 1,
      anon_sym_COMMA,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(70), 1,
      aux_sym_fact_repeat1,
    STATE(126), 1,
      sym_sp,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1112] = 3,
    ACTIONS(144), 1,
      aux_sym_nname_token2,
    STATE(46), 1,
      aux_sym_nname_repeat1,
    ACTIONS(117), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1127] = 1,
    ACTIONS(147), 7,
      anon_sym_SEMI,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1137] = 1,
    ACTIONS(149), 7,
      anon_sym_SEMI,
      anon_sym_LT_DASH,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1147] = 1,
    ACTIONS(151), 7,
      anon_sym_SEMI,
      anon_sym_LT_DASH,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1157] = 3,
    ACTIONS(155), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_rule_body_repeat1,
    ACTIONS(153), 5,
      anon_sym_SEMI,
      anon_sym_or,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1171] = 1,
    ACTIONS(157), 7,
      anon_sym_SEMI,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1181] = 1,
    ACTIONS(159), 7,
      anon_sym_SEMI,
      anon_sym_LT_DASH,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1191] = 1,
    ACTIONS(161), 7,
      anon_sym_SEMI,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1201] = 1,
    ACTIONS(163), 7,
      anon_sym_SEMI,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1211] = 1,
    ACTIONS(165), 7,
      anon_sym_SEMI,
      anon_sym_LT_DASH,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1221] = 3,
    ACTIONS(169), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_rule_body_repeat1,
    ACTIONS(167), 5,
      anon_sym_SEMI,
      anon_sym_or,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1235] = 1,
    ACTIONS(172), 7,
      anon_sym_SEMI,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1245] = 3,
    ACTIONS(155), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_rule_body_repeat1,
    ACTIONS(174), 5,
      anon_sym_SEMI,
      anon_sym_or,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1259] = 1,
    ACTIONS(176), 7,
      anon_sym_SEMI,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1269] = 3,
    ACTIONS(180), 1,
      anon_sym_or,
    STATE(80), 1,
      aux_sym_check_repeat1,
    ACTIONS(178), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1282] = 1,
    ACTIONS(182), 6,
      anon_sym_SEMI,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1291] = 3,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_rule_body_repeat1,
    ACTIONS(153), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1304] = 4,
    ACTIONS(186), 1,
      anon_sym_SEMI,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(127), 1,
      sym_sp,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1319] = 3,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      aux_sym_predicate_repeat1,
    ACTIONS(191), 4,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1332] = 4,
    ACTIONS(193), 1,
      anon_sym_LT_DASH,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(125), 1,
      sym_sp,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1347] = 3,
    ACTIONS(180), 1,
      anon_sym_or,
    STATE(74), 1,
      aux_sym_check_repeat1,
    ACTIONS(195), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1360] = 3,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_rule_body_repeat1,
    ACTIONS(174), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1373] = 2,
    ACTIONS(73), 1,
      aux_sym_nname_token1,
    ACTIONS(71), 5,
      ts_builtin_sym_end,
      anon_sym_checkif,
      anon_sym_checkall,
      anon_sym_allowif,
      anon_sym_denyif,
  [1384] = 3,
    ACTIONS(180), 1,
      anon_sym_or,
    STATE(73), 1,
      aux_sym_check_repeat1,
    ACTIONS(197), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1397] = 3,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_fact_repeat1,
    ACTIONS(202), 4,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1410] = 3,
    ACTIONS(180), 1,
      anon_sym_or,
    STATE(80), 1,
      aux_sym_check_repeat1,
    ACTIONS(204), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1423] = 3,
    ACTIONS(180), 1,
      anon_sym_or,
    STATE(60), 1,
      aux_sym_check_repeat1,
    ACTIONS(206), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1436] = 3,
    ACTIONS(180), 1,
      anon_sym_or,
    STATE(80), 1,
      aux_sym_check_repeat1,
    ACTIONS(206), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1449] = 3,
    ACTIONS(180), 1,
      anon_sym_or,
    STATE(80), 1,
      aux_sym_check_repeat1,
    ACTIONS(208), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1462] = 2,
    ACTIONS(212), 1,
      aux_sym_nname_token1,
    ACTIONS(210), 5,
      ts_builtin_sym_end,
      anon_sym_checkif,
      anon_sym_checkall,
      anon_sym_allowif,
      anon_sym_denyif,
  [1473] = 1,
    ACTIONS(214), 6,
      anon_sym_SEMI,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1482] = 3,
    ACTIONS(180), 1,
      anon_sym_or,
    STATE(71), 1,
      aux_sym_check_repeat1,
    ACTIONS(208), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1495] = 1,
    ACTIONS(167), 6,
      anon_sym_SEMI,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1504] = 3,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_rule_body_repeat1,
    ACTIONS(167), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1517] = 3,
    ACTIONS(221), 1,
      anon_sym_or,
    STATE(80), 1,
      aux_sym_check_repeat1,
    ACTIONS(219), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1530] = 1,
    ACTIONS(224), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1538] = 1,
    ACTIONS(191), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1546] = 1,
    ACTIONS(226), 5,
      anon_sym_SEMI,
      anon_sym_or,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1554] = 1,
    ACTIONS(228), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1562] = 1,
    ACTIONS(231), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1570] = 1,
    ACTIONS(233), 5,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1578] = 1,
    ACTIONS(235), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1586] = 1,
    ACTIONS(202), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1594] = 3,
    STATE(24), 1,
      aux_sym_sp_repeat1,
    STATE(93), 1,
      sym_sp,
    ACTIONS(103), 3,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1606] = 1,
    ACTIONS(237), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1613] = 1,
    ACTIONS(239), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1620] = 1,
    ACTIONS(241), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1627] = 4,
    ACTIONS(243), 1,
      aux_sym_nname_token1,
    STATE(58), 1,
      sym_predicate,
    STATE(83), 1,
      sym_rule_body,
    STATE(122), 1,
      sym_nname,
  [1640] = 1,
    ACTIONS(245), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1647] = 4,
    ACTIONS(243), 1,
      aux_sym_nname_token1,
    STATE(67), 1,
      sym_predicate,
    STATE(101), 1,
      sym_rule_body,
    STATE(122), 1,
      sym_nname,
  [1660] = 4,
    ACTIONS(243), 1,
      aux_sym_nname_token1,
    STATE(67), 1,
      sym_predicate,
    STATE(94), 1,
      sym_rule_body,
    STATE(122), 1,
      sym_nname,
  [1673] = 4,
    ACTIONS(243), 1,
      aux_sym_nname_token1,
    STATE(58), 1,
      sym_predicate,
    STATE(72), 1,
      sym_rule_body,
    STATE(122), 1,
      sym_nname,
  [1686] = 1,
    ACTIONS(247), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1693] = 4,
    ACTIONS(243), 1,
      aux_sym_nname_token1,
    STATE(58), 1,
      sym_predicate,
    STATE(77), 1,
      sym_rule_body,
    STATE(122), 1,
      sym_nname,
  [1706] = 1,
    ACTIONS(249), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1713] = 1,
    ACTIONS(251), 4,
      anon_sym_SEMI,
      anon_sym_,
      anon_sym_TAB,
      anon_sym_LF,
  [1720] = 3,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    ACTIONS(255), 1,
      anon_sym_RBRACK,
    STATE(106), 1,
      aux_sym_set_repeat1,
  [1730] = 3,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    ACTIONS(257), 1,
      anon_sym_RBRACK,
    STATE(110), 1,
      aux_sym_set_repeat1,
  [1740] = 3,
    ACTIONS(259), 1,
      anon_sym_LPAREN,
    ACTIONS(261), 1,
      aux_sym_nname_token2,
    STATE(108), 1,
      aux_sym_nname_repeat1,
  [1750] = 3,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    ACTIONS(257), 1,
      anon_sym_RBRACK,
    STATE(109), 1,
      aux_sym_set_repeat1,
  [1760] = 3,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    ACTIONS(263), 1,
      anon_sym_RBRACK,
    STATE(110), 1,
      aux_sym_set_repeat1,
  [1770] = 3,
    ACTIONS(265), 1,
      anon_sym_LPAREN,
    ACTIONS(267), 1,
      aux_sym_nname_token2,
    STATE(104), 1,
      aux_sym_nname_repeat1,
  [1780] = 3,
    ACTIONS(269), 1,
      anon_sym_LPAREN,
    ACTIONS(271), 1,
      aux_sym_nname_token2,
    STATE(108), 1,
      aux_sym_nname_repeat1,
  [1790] = 3,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    ACTIONS(255), 1,
      anon_sym_RBRACK,
    STATE(110), 1,
      aux_sym_set_repeat1,
  [1800] = 3,
    ACTIONS(87), 1,
      anon_sym_RBRACK,
    ACTIONS(274), 1,
      anon_sym_COMMA,
    STATE(110), 1,
      aux_sym_set_repeat1,
  [1810] = 1,
    ACTIONS(277), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1815] = 1,
    ACTIONS(87), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1820] = 1,
    ACTIONS(279), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1825] = 2,
    ACTIONS(281), 1,
      aux_sym_nname_token2,
    STATE(37), 1,
      aux_sym_nname_repeat1,
  [1832] = 2,
    ACTIONS(283), 1,
      aux_sym_nname_token2,
    STATE(38), 1,
      aux_sym_nname_repeat1,
  [1839] = 1,
    ACTIONS(285), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1844] = 1,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
  [1848] = 1,
    ACTIONS(289), 1,
      anon_sym_RPAREN,
  [1852] = 1,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
  [1856] = 1,
    ACTIONS(293), 1,
      anon_sym_LPAREN,
  [1860] = 1,
    ACTIONS(295), 1,
      anon_sym_RPAREN,
  [1864] = 1,
    ACTIONS(297), 1,
      anon_sym_LPAREN,
  [1868] = 1,
    ACTIONS(299), 1,
      anon_sym_RPAREN,
  [1872] = 1,
    ACTIONS(301), 1,
      ts_builtin_sym_end,
  [1876] = 1,
    ACTIONS(303), 1,
      anon_sym_LT_DASH,
  [1880] = 1,
    ACTIONS(305), 1,
      anon_sym_RPAREN,
  [1884] = 1,
    ACTIONS(307), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 46,
  [SMALL_STATE(4)] = 92,
  [SMALL_STATE(5)] = 133,
  [SMALL_STATE(6)] = 169,
  [SMALL_STATE(7)] = 205,
  [SMALL_STATE(8)] = 242,
  [SMALL_STATE(9)] = 279,
  [SMALL_STATE(10)] = 311,
  [SMALL_STATE(11)] = 333,
  [SMALL_STATE(12)] = 355,
  [SMALL_STATE(13)] = 387,
  [SMALL_STATE(14)] = 418,
  [SMALL_STATE(15)] = 449,
  [SMALL_STATE(16)] = 480,
  [SMALL_STATE(17)] = 512,
  [SMALL_STATE(18)] = 539,
  [SMALL_STATE(19)] = 566,
  [SMALL_STATE(20)] = 588,
  [SMALL_STATE(21)] = 610,
  [SMALL_STATE(22)] = 629,
  [SMALL_STATE(23)] = 652,
  [SMALL_STATE(24)] = 675,
  [SMALL_STATE(25)] = 692,
  [SMALL_STATE(26)] = 711,
  [SMALL_STATE(27)] = 728,
  [SMALL_STATE(28)] = 752,
  [SMALL_STATE(29)] = 776,
  [SMALL_STATE(30)] = 800,
  [SMALL_STATE(31)] = 824,
  [SMALL_STATE(32)] = 846,
  [SMALL_STATE(33)] = 867,
  [SMALL_STATE(34)] = 888,
  [SMALL_STATE(35)] = 909,
  [SMALL_STATE(36)] = 930,
  [SMALL_STATE(37)] = 945,
  [SMALL_STATE(38)] = 960,
  [SMALL_STATE(39)] = 975,
  [SMALL_STATE(40)] = 986,
  [SMALL_STATE(41)] = 1007,
  [SMALL_STATE(42)] = 1028,
  [SMALL_STATE(43)] = 1049,
  [SMALL_STATE(44)] = 1070,
  [SMALL_STATE(45)] = 1091,
  [SMALL_STATE(46)] = 1112,
  [SMALL_STATE(47)] = 1127,
  [SMALL_STATE(48)] = 1137,
  [SMALL_STATE(49)] = 1147,
  [SMALL_STATE(50)] = 1157,
  [SMALL_STATE(51)] = 1171,
  [SMALL_STATE(52)] = 1181,
  [SMALL_STATE(53)] = 1191,
  [SMALL_STATE(54)] = 1201,
  [SMALL_STATE(55)] = 1211,
  [SMALL_STATE(56)] = 1221,
  [SMALL_STATE(57)] = 1235,
  [SMALL_STATE(58)] = 1245,
  [SMALL_STATE(59)] = 1259,
  [SMALL_STATE(60)] = 1269,
  [SMALL_STATE(61)] = 1282,
  [SMALL_STATE(62)] = 1291,
  [SMALL_STATE(63)] = 1304,
  [SMALL_STATE(64)] = 1319,
  [SMALL_STATE(65)] = 1332,
  [SMALL_STATE(66)] = 1347,
  [SMALL_STATE(67)] = 1360,
  [SMALL_STATE(68)] = 1373,
  [SMALL_STATE(69)] = 1384,
  [SMALL_STATE(70)] = 1397,
  [SMALL_STATE(71)] = 1410,
  [SMALL_STATE(72)] = 1423,
  [SMALL_STATE(73)] = 1436,
  [SMALL_STATE(74)] = 1449,
  [SMALL_STATE(75)] = 1462,
  [SMALL_STATE(76)] = 1473,
  [SMALL_STATE(77)] = 1482,
  [SMALL_STATE(78)] = 1495,
  [SMALL_STATE(79)] = 1504,
  [SMALL_STATE(80)] = 1517,
  [SMALL_STATE(81)] = 1530,
  [SMALL_STATE(82)] = 1538,
  [SMALL_STATE(83)] = 1546,
  [SMALL_STATE(84)] = 1554,
  [SMALL_STATE(85)] = 1562,
  [SMALL_STATE(86)] = 1570,
  [SMALL_STATE(87)] = 1578,
  [SMALL_STATE(88)] = 1586,
  [SMALL_STATE(89)] = 1594,
  [SMALL_STATE(90)] = 1606,
  [SMALL_STATE(91)] = 1613,
  [SMALL_STATE(92)] = 1620,
  [SMALL_STATE(93)] = 1627,
  [SMALL_STATE(94)] = 1640,
  [SMALL_STATE(95)] = 1647,
  [SMALL_STATE(96)] = 1660,
  [SMALL_STATE(97)] = 1673,
  [SMALL_STATE(98)] = 1686,
  [SMALL_STATE(99)] = 1693,
  [SMALL_STATE(100)] = 1706,
  [SMALL_STATE(101)] = 1713,
  [SMALL_STATE(102)] = 1720,
  [SMALL_STATE(103)] = 1730,
  [SMALL_STATE(104)] = 1740,
  [SMALL_STATE(105)] = 1750,
  [SMALL_STATE(106)] = 1760,
  [SMALL_STATE(107)] = 1770,
  [SMALL_STATE(108)] = 1780,
  [SMALL_STATE(109)] = 1790,
  [SMALL_STATE(110)] = 1800,
  [SMALL_STATE(111)] = 1810,
  [SMALL_STATE(112)] = 1815,
  [SMALL_STATE(113)] = 1820,
  [SMALL_STATE(114)] = 1825,
  [SMALL_STATE(115)] = 1832,
  [SMALL_STATE(116)] = 1839,
  [SMALL_STATE(117)] = 1844,
  [SMALL_STATE(118)] = 1848,
  [SMALL_STATE(119)] = 1852,
  [SMALL_STATE(120)] = 1856,
  [SMALL_STATE(121)] = 1860,
  [SMALL_STATE(122)] = 1864,
  [SMALL_STATE(123)] = 1868,
  [SMALL_STATE(124)] = 1872,
  [SMALL_STATE(125)] = 1876,
  [SMALL_STATE(126)] = 1880,
  [SMALL_STATE(127)] = 1884,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_sp_repeat1, 2),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sp_repeat1, 2), SHIFT_REPEAT(10),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sp, 1),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_set_repeat1, 1),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(30),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(28),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(107),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_authorizer_element, 3),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_authorizer_element, 3),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_authorizer_element, 2),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_authorizer_element, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sp, 1),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sp_repeat1, 2),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sp_repeat1, 2), SHIFT_REPEAT(25),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sp_repeat1, 2), SHIFT_REPEAT(26),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_nname_repeat1, 2),
  [119] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_nname_repeat1, 2), SHIFT_REPEAT(36),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 2),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [144] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_nname_repeat1, 2), SHIFT_REPEAT(46),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 4),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_predicate, 4),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_predicate, 5),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule_body, 2),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 1),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_predicate, 6),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 3),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 5),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_predicate, 7),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rule_body_repeat1, 2),
  [169] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rule_body_repeat1, 2), SHIFT_REPEAT(3),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 6),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule_body, 1),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 2),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_policy, 4),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rule_body_repeat1, 3),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [188] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_predicate_repeat1, 2), SHIFT_REPEAT(5),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_predicate_repeat1, 2),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_check, 2),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_policy, 2),
  [199] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fact_repeat1, 2), SHIFT_REPEAT(9),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_fact_repeat1, 2),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_check, 4),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_policy, 3),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_check, 3),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_authorizer_element, 4),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_authorizer_element, 4),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [216] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rule_body_repeat1, 2), SHIFT_REPEAT(2),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_check_repeat1, 2),
  [221] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_check_repeat1, 2), SHIFT_REPEAT(89),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_fact_repeat1, 3),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_check_repeat1, 3),
  [228] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_term, 1), REDUCE(sym_fact_term, 1),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_predicate_repeat1, 3),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_term, 1),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fact_term, 1),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 3),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fact, 6),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fact, 5),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 4),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fact, 4),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fact, 7),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 5),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nname, 2),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nname, 1),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nname_repeat1, 2),
  [271] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nname_repeat1, 2), SHIFT_REPEAT(108),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2), SHIFT_REPEAT(12),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_term, 1),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 3),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [301] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_biscuit(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
